---
jobs:
- name: say_hello
  plan:
  - task: say_hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: echo
        args: ["Hello, world!"]
